"""Review index over original raw samples; no motion concatenation or correction."""
import copy,html,json,os
from pathlib import Path
BASE=Path('/media/ipsedesktop/ShareDrive1/ModelData/aniMove/unimate');out=BASE/'pilgrim_support_review_001';out.mkdir(exist_ok=False)
a=json.loads((BASE/'pilgrim_support_001/run.json').read_text());b=json.loads((BASE/'pilgrim_support_short_001/run.json').read_text());assert len(a['runs'])==18 and len(b['runs'])==9
old=json.loads((BASE/'pilgrim_harvest_001/run.json').read_text());ref=copy.deepcopy(next(r for r in old['runs'] if r['label']=='p07' and r['seed']==9400));ref['label']='support_prior_biped';ref['variant']='prior_arms_legs';ref['prompt_id']='walk';ref['reference_only']=True
m=dict(status='raw_feasibility_review',object='Pilgrim',frames=60,fps=30,cfg=3.0,checkpoint_sha256=a['checkpoint_sha256'],source_revision=a['source_revision'],source_manifests=[str(BASE/n/'run.json') for n in ['pilgrim_support_001','pilgrim_support_short_001','pilgrim_harvest_001']],runs=[ref]+a['runs']+b['runs']);(out/'run.json').write_text(json.dumps(m,indent=2)+'\n')
reports=[json.loads((BASE/n/'support_analysis.json').read_text()) for n in ['pilgrim_support_001','pilgrim_support_short_001']];records=reports[0]['records']+reports[1]['records'];(out/'support_analysis.json').write_text(json.dumps(dict(screen=reports[0]['screen'],passes=reports[0]['passes']+reports[1]['passes'],records=records),indent=2)+'\n')
page=['<!doctype html><html><head><meta charset="utf-8"><title>Pilgrim support study</title><style>body{font:17px system-ui;background:#121922;color:#eee;max-width:1000px;margin:auto;padding:40px;line-height:1.6}a{color:#7dd9e9}video{width:100%}</style></head><body><h1>Biped → quadruped → biped: feasibility review</h1><p>27 new raw two-second clips plus the previous bipedal walking reference. This is a review collection, not a generated transition sequence or seamless loop.</p><ul><li><a href="../pilgrim_support_001/review/index.html">18 detailed-prompt samples · both name schemes</a></li><li><a href="../pilgrim_support_short_001/review/index.html">9 short-prompt samples · front/hind names</a></li><li><a href="support_review.blend">Blender master with all 28 Actions</a></li><li><a href="support_analysis.json">Support diagnostics</a></li></ul><h2>Earlier bipedal walking reference · p07 / 9400</h2>']
video=next((Path(ref['path'])/'samples/animations').glob('*_fk.mp4'));page.append('<video controls loop muted src="'+html.escape(os.path.relpath(video,out))+'"></video></body></html>');(out/'index.html').write_text('\n'.join(page));print('Combined',len(m['runs']))
